# hash:sha256:2cdfaf2f2954362f9773332c899a09db4ae553ef4bbcce7700ec9becc8a64077
FROM registry.codeocean.com/codeocean/miniconda3:4.6.14-python3.7.3-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    matplotlib==3.4.1 \
    nltk==3.6.1 \
    pandas==1.2.3 \
    scikit-learn==0.24.1
